EdmureBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),
    path('backend/', include('backend.urls')),
    path('', include('web.urls')),
]

web/urls.py
from django.conf.urls import url
from web.views import home
from web.views import login_register
from web.views import  my_home


urlpatterns = [
    url(r'^$', home.to_home),
    url(r"^login_register.html$", login_register.show_page, name='show_login_page'),
    url(r"^register$", login_register.register, name="register"),
    url(r"^check_code$", login_register.check_code, name="check_code"),
    url(r"^login$", login_register.login, name="login"),
    url(r"^logout$", login_register.logout, name="logout"),
    url(r'^home.html-(?P<category>\d+)$', home.home, name='home'),
    url(r'^my_home/(?P<surfix>\w+).html$', my_home.my_home, name="my_home"),
    url(r"^my_home/(?P<surfix>\w+)/(?P<category>(category)|(tag)|(time))/(?P<num>\d+-*\d*).html$",  # 0  2017-1
        my_home.article_filter, name="article_filter"),
    url(r"^article_detail/(?P<surfix>\w+)/(?P<article_id>\d+).html$", my_home.article_detail, name="article_detail"),
    url(r"^save_comment$", my_home.save_comment, name="save_comment"),
    url(r'^comment_page_nation$', my_home.comment_page_nation, name="comment_page_nation"),
    url(r'^thumb$', my_home.thumb, name="thumb"),
    url(r'^re_comment$', my_home.re_comment, name="re_comment"),
]

repository/models.py
from django.db import models


# 用户信息表
class User(models.Model):
    username = models.CharField(max_length=16, unique=True, verbose_name="用户名")
    pwd = models.CharField(max_length=32, verbose_name="密码")
    email = models.CharField(max_length=32, unique=True, verbose_name="邮箱")
    img = models.CharField(verbose_name="头像", null=True, blank=True, max_length=256)
    fans = models.ManyToManyField(to="User", related_name="refans", blank=True)

    class Meta:
        verbose_name_plural = "用户表"
        db_table = "User"

    def __str__(self):
        return self.username


# 博客表
class Blog(models.Model):
    theme = models.CharField(max_length=8, verbose_name="博客主题", blank=True, null=True)
    title = models.CharField(max_length=16, verbose_name="博客标题", blank=True, null=True)
    summary = models.CharField(max_length=64, verbose_name="基本简介", blank=True, null=True)
    surfix = models.CharField(max_length=32, verbose_name="后缀", unique=True)
    user = models.OneToOneField(to="User", to_field="id", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "博客表"
        db_table = "Blog"


# 分类表
class Category(models.Model):
    caption = models.CharField(max_length=8, unique=True, verbose_name="类别")
    blog = models.ForeignKey(to="Blog", to_field="id", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

    class Meta:
        db_table = "Category"
        verbose_name_plural = "分类表"


# 标签表
class Tag(models.Model):
    caption = models.CharField(max_length=8, unique=True, verbose_name="标签类别")
    blog = models.ForeignKey(to="Blog", to_field="id", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

    class Meta:
        db_table = "Tag"
        verbose_name_plural = "标签表"


# 文章表
class Article(models.Model):
    title = models.CharField(max_length=16, verbose_name="标题")
    summary = models.CharField(max_length=256, verbose_name="基本简介")
    detail = models.TextField(verbose_name="具体文章")
    ctime = models.DateTimeField(auto_now=True, verbose_name="创建时间")
    category_choice = ((1, "Python"), (2, "Golang"), (3, "Linux运维"), (4, "Java"), )
    main_stack_category = models.IntegerField(choices=category_choice, verbose_name="主站分类")
    category = models.ForeignKey(to="Category", to_field='id', on_delete=models.CASCADE, null=True, blank=True)
    tag = models.ManyToManyField(to="Tag", blank=True)
    user = models.ForeignKey(to="User", to_field='id', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        db_table = "Article"
        verbose_name_plural = "文章表"


# 赞踩文章关系表
class ThumbUp(models.Model):
    article = models.ForeignKey(to="Article", to_field="id", verbose_name="文章id", on_delete=models.CASCADE)
    user = models.ForeignKey(to="User", to_field='id', verbose_name="用户ID", on_delete=models.CASCADE)
    is_thumb_up = models.BooleanField()

    class Meta:
        db_table = "ThumbUp"
        verbose_name_plural = "赞踩文章关系表"
        unique_together = (("article", "user"), )


# 评论表
class Comment(models.Model):
    content = models.TextField(verbose_name="评论内容")
    ctime = models.DateTimeField(auto_now=True, verbose_name="评论时间")
    user = models.ForeignKey(to="User", to_field='id', on_delete=models.CASCADE, verbose_name="评论人")
    article = models.ForeignKey(to="Article", to_field='id', on_delete=models.CASCADE, verbose_name="评论文章")
    parent_comment = models.ForeignKey(to="Comment", to_field='id', on_delete=models.CASCADE,
                                       verbose_name="父评论", null=True, blank=True)

    def __str__(self):
        return self.user.username + "--->" + self.content

    class Meta:
        db_table = "Comment"
        verbose_name_plural = "评论表"


# 报障表
class Trouble(models.Model):
    title = models.CharField(max_length=64, verbose_name="报障标题")
    detail = models.TextField(verbose_name="故障描述")
    sender = models.ForeignKey(to="User", to_field="id", on_delete=models.CASCADE, related_name="sender", verbose_name="提交者")
    ctime = models.CharField(max_length=32, verbose_name="创建时间")
    status_choices = ((1, "未处理"), (2, "处理中"), (3, "已处理"), )
    status = models.IntegerField(choices=status_choices, verbose_name="障单状态")
    handler = models.ForeignKey(to="User", to_field="id", on_delete=models.CASCADE, null=True, blank=True)
    solve_plan = models.TextField(verbose_name="解决方案", null=True, blank=True)
    stime = models.CharField(max_length=32, verbose_name="解决时间", null=True, blank=True)
    evaluate_choices = ((1, "活儿不行"), (2, "一般"), (3, "活儿很好"), )
    evaluate = models.IntegerField(choices=evaluate_choices, verbose_name="评价", null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = "Trouble"
        verbose_name_plural = "报障表"


# 权限管理相关表


# 角色表
class Role(models.Model):
    caption = models.CharField(max_length=32)

    class Meta:
        db_table = "role"
        verbose_name_plural = '角色表'

    def __str__(self):
        return self.caption


# 用户角色关联表
class User2Role(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)

    class Meta:
        db_table = "user2role"
        verbose_name_plural = '用户分配角色'

    def __str__(self):
        return "%s-%s" % (self.user.username, self.role.caption,)


# 权限表
class Action(models.Model):
    # get  获取用户信息1
    # post  创建用户2
    # delete 删除用户3
    # put  修改用户4
    caption = models.CharField(max_length=32)
    code = models.CharField(max_length=32)

    class Meta:
        db_table = 'action'
        verbose_name_plural = '操作表'

    def __str__(self):
        return self.caption


# 1    菜单1     null
# 2    菜单2     null
# 3    菜单3     null
# 4    菜单1.1    1
# 5    菜单1.2    1
# 6    菜单1.2.1  4
# 无最后一层
class Menu(models.Model):
    caption = models.CharField(max_length=32)
    parent = models.ForeignKey('self', related_name='p', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return "%s" % (self.caption,)


# URL表
class Permission(models.Model):
    # http://127.0.0.1:8001/user.html  用户管理 1
    # http://127.0.0.1:8001/order.html 订单管理 1
    caption = models.CharField(max_length=32)
    url = models.CharField(max_length=64)
    menu = models.ForeignKey(Menu, null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        db_table = 'permission'
        verbose_name_plural = 'URL表'

    def __str__(self):
        return "%s-%s" % (self.caption, self.url,)


# URL跟权限关联表
class Permission2Action(models.Model):
    permission = models.ForeignKey(Permission, on_delete=models.CASCADE)
    action = models.ForeignKey(Action, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '权限表'

    def __str__(self):
        return "%s-%s:-%s?t=%s" % (self.permission.caption, self.action.caption, self.permission.url, self.action.code,)


# 角色跟权限关联表
class Permission2Action2Role(models.Model):
    p2a = models.ForeignKey(Permission2Action, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '角色分配权限'

    def __str__(self):
        return "%s==>%s" % (self.role.caption, self.p2a,)

web/views/home.py
from django.shortcuts import render, redirect
from repository import models
from django.urls import reverse
from utils.pageNation import Pagenation


# Create your views here.


# Global variable
PER_PAGE = 5     # 每一页显示的数目
MOST_COMMENTS = 8   # 评论最多的文章


# 跳转到主页面
def to_home(request):
    # 获取主页面的url
    path = reverse("home", kwargs={"category": 0})
    return redirect(path)


# 博客主页
def home(request, category):
    # 获取用户信息
    user_info = request.session.get("user", None)
    # 获取用户后缀
    if user_info:
        blog = models.Blog.objects.filter(user_id=user_info['id'])
        if blog:
            user_surfix = blog[0].surfix
        else:
            user_surfix = ''
    else:
        user_surfix = ''
    # 获取前端参数
    params = request.GET.get("page", None)
    try:
        current_page = int(params)
        if current_page <= 0:
            current_page = 1
    except TypeError:
        current_page = 1
    # 获取主站类型,并判断category是否超出了主站能表示范围
    stack_choices = models.Article.category_choice
    category_num = int(category)
    for i in stack_choices:
        if i[0] == category_num:
            break
    else:
        category_num = 0
    # 获取对应主站的文章
    if category_num == 0:
        articles = models.Article.objects.all()
    else:
        articles = models.Article.objects.filter(main_stack_category=category_num)
    # 准备分页
    url = reverse("home", kwargs={"category": category_num})    # 获取当前视图函数对应的url
    page_nation = Pagenation(articles.count(), current_page, PER_PAGE, url=url)   # 创建分页对象
    articles = articles[page_nation.start_index:page_nation.end_index]   # 获取当前页要展示的文章

    # 获取评论最多的文章
    sql = """
        SELECT a.id, a.title, a.user_id FROM article AS a, 
        (SELECT article_id, count(*) as num FROM comment GROUP BY article_id) As c WHERE
        a.id = c.article_id ORDER BY c.num DESC LIMIT 0, %s
    """
    comments_articles = models.Article.objects.raw(sql, params=[MOST_COMMENTS, ])

    return render(request, "home/home.html", {
        "articles": articles,
        "stack_choices": stack_choices,
        "current_category": category_num,
        "page_nation": page_nation,
        "user_info": user_info,
        'user_surfix': user_surfix,
        'comments_info': comments_articles
    })

templates/home/home.html
{% load staticfiles %}
{% load count_article %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客主页</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
            <div class="navbar-header">
              <a class="navbar-brand" href="#">老子的技术论坛</a>
            </div>
            <div class="collapse navbar-collapse navbar-min" id="bs-example-navbar-collapse-6">
                <ul class="nav navbar-nav">
                    {% if current_category == 0 %}
                      <li class="active"><a href="{% url 'home' 0 %}">全部</a></li>
                    {% else %}
                      <li><a href="{% url 'home' 0 %}">全部</a></li>
                    {% endif %}
                    {% for category in stack_choices %}
                        {% if category.0 == current_category %}
                          <li class="active"><a href="{% url 'home' category.0 %}">{{ category.1 }}</a></li>
                        {% else %}
                          <li><a href="{% url 'home' category.0 %}">{{ category.1 }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
                <ul class="nav navbar-right navbar-nav">
                    {% if user_info %}
                        {% if user_surfix != "" %}
                            <li><a href="{% url 'my_home' user_surfix %}">{{ user_info.username }}</a></li>
                            <li><a href="{% url 'my_home' user_surfix %}">我的博客</a></li>
                        {% else %}
                            <li><a href="javascript:void(0);" onclick="p_login();">{{ user_info.username }}</a></li>
                            <li><a href="javascript:void(0);" onclick="p_login();">我的博客</a></li>
                        {% endif %}
                        <li><a href="{% url 'index' %}">管理</a></li>
                        <li><a href="{% url "logout" %}">退出</a></li>
                    {% else %}
                        <li><a href="{% url "show_login_page" %}">登陆</a></li>
                        <li><a href="{% url "show_login_page" %}">注册</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="middle-content clearFloat">
        <div class="m-left">
            {% for article in articles %}
            <div class="article">
                <ul class="article-list">
                    <li class="article-title">
                        <a href="{% url 'article_detail' article.id|surfix_by_article article.id %}">{{ article.title }}</a>
                    </li>
                    <li class="article-content clearFloat">
                        <img src="{% static 'images/1.jpg' %}" alt="IMG" height="80px" width="80px">
                        <span>{{ article.summary }}</span>
                    </li>
                    <li class="article-info">
                        <i class="glyphicon glyphicon-fire"></i>
                        <a href="#">{{ article.user.username }}</a> 发布于 <span>{{ article.ctime|date:'Y-m-d' }}</span>
                        <span class="comment-thumb-up">
                            <span class="comment">
                                <i class="glyphicon glyphicon-menu-hamburger"></i>
                                <span>{{ article.comment_set.all.count }}</span>
                            </span>
                            <span class="thumb-up">
                                <i class="glyphicon glyphicon-thumbs-up"></i>
                                <span>{{ article.thumbup_set.all.count }}</span>
                            </span>
                        </span>
                    </li>
                </ul>
            </div>
            {% endfor %}
            <div class="pagenation">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if page_nation.current_page == 1 %}
                            <li class="disabled">
                                <a href="javascript:void(0);" aria-label="Previous">
                                    <span aria-hidden="true">上一页</span>
                                </a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{{ page_nation.url }}?page={{ page_nation.previous_page }}" aria-label="Previous">
                                    <span aria-hidden="true">上一页</span>
                                </a>
                            </li>
                        {% endif %}

                        {% for page in page_nation.page_nation %}
                            {% if page == page_nation.current_page %}
                                <li class="active"><a href="javascript:void(0);">{{ page}}</a></li>
                            {% else %}
                                <li><a href="{{ page_nation.url }}?page={{ page }}">{{ page }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if page_nation.current_page == page_nation.max_page %}
                            <li class="disabled">
                                <a href="javascript:void(0);" aria-label="Next">
                                    <span aria-hidden="true">下一页</span>
                                </a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{{ page_nation.url }}?page={{ page_nation.next_page }}" aria-label="Next">
                                    <span aria-hidden="true">下一页</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
        <div class="m-right">
            <div class="sincerely-recommand">
                <div class="title">热血推荐</div>
                {% for comment_article in comments_info %}
                <div class="re-article"><a href="{% url 'article_detail' comment_article.user_id|surfix_by_user comment_article.id %}">{{ comment_article.title }}</a></div>
                {% endfor %}
            </div>
            <div class="the-most-comment">
                <div class="title">评论最多</div>
                {% for comment_article in comments_info %}
                <div class="re-article"><a href="{% url 'article_detail' comment_article.user_id|surfix_by_user comment_article.id %}">{{ comment_article.title }}</a></div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script>
        function p_login(){
            alert("您还没有开通博客，点击管理进行开通吧~~");
        }
    </script>
</body>
</html>