EdmureBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),
    path('backend/', include('backend.urls')),
    path('', include('web.urls')),
]

web/urls.py
from django.conf.urls import url
from web.views import home
from web.views import login_register
from web.views import  my_home


urlpatterns = [
    url(r'^$', home.to_home),
    url(r"^login_register.html$", login_register.show_page, name='show_login_page'),
    url(r"^register$", login_register.register, name="register"),
    url(r"^check_code$", login_register.check_code, name="check_code"),
    url(r"^login$", login_register.login, name="login"),
    url(r"^logout$", login_register.logout, name="logout"),
    url(r'^home.html-(?P<category>\d+)$', home.home, name='home'),
    url(r'^my_home/(?P<surfix>\w+).html$', my_home.my_home, name="my_home"),
    url(r"^my_home/(?P<surfix>\w+)/(?P<category>(category)|(tag)|(time))/(?P<num>\d+-*\d*).html$",  # 0  2017-1
        my_home.article_filter, name="article_filter"),
    url(r"^article_detail/(?P<surfix>\w+)/(?P<article_id>\d+).html$", my_home.article_detail, name="article_detail"),
    url(r"^save_comment$", my_home.save_comment, name="save_comment"),
    url(r'^comment_page_nation$', my_home.comment_page_nation, name="comment_page_nation"),
    url(r'^thumb$', my_home.thumb, name="thumb"),
    url(r'^re_comment$', my_home.re_comment, name="re_comment"),
]

repository/models.py
from django.db import models


# 用户信息表
class User(models.Model):
    username = models.CharField(max_length=16, unique=True, verbose_name="用户名")
    pwd = models.CharField(max_length=32, verbose_name="密码")
    email = models.CharField(max_length=32, unique=True, verbose_name="邮箱")
    img = models.CharField(verbose_name="头像", null=True, blank=True, max_length=256)
    fans = models.ManyToManyField(to="User", related_name="refans", blank=True)

    class Meta:
        verbose_name_plural = "用户表"
        db_table = "User"

    def __str__(self):
        return self.username


# 博客表
class Blog(models.Model):
    theme = models.CharField(max_length=8, verbose_name="博客主题", blank=True, null=True)
    title = models.CharField(max_length=16, verbose_name="博客标题", blank=True, null=True)
    summary = models.CharField(max_length=64, verbose_name="基本简介", blank=True, null=True)
    surfix = models.CharField(max_length=32, verbose_name="后缀", unique=True)
    user = models.OneToOneField(to="User", to_field="id", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "博客表"
        db_table = "Blog"


# 分类表
class Category(models.Model):
    caption = models.CharField(max_length=8, unique=True, verbose_name="类别")
    blog = models.ForeignKey(to="Blog", to_field="id", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

    class Meta:
        db_table = "Category"
        verbose_name_plural = "分类表"


# 标签表
class Tag(models.Model):
    caption = models.CharField(max_length=8, unique=True, verbose_name="标签类别")
    blog = models.ForeignKey(to="Blog", to_field="id", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

    class Meta:
        db_table = "Tag"
        verbose_name_plural = "标签表"


# 文章表
class Article(models.Model):
    title = models.CharField(max_length=16, verbose_name="标题")
    summary = models.CharField(max_length=256, verbose_name="基本简介")
    detail = models.TextField(verbose_name="具体文章")
    ctime = models.DateTimeField(auto_now=True, verbose_name="创建时间")
    category_choice = ((1, "Python"), (2, "Golang"), (3, "Linux运维"), (4, "Java"), )
    main_stack_category = models.IntegerField(choices=category_choice, verbose_name="主站分类")
    category = models.ForeignKey(to="Category", to_field='id', on_delete=models.CASCADE, null=True, blank=True)
    tag = models.ManyToManyField(to="Tag", blank=True)
    user = models.ForeignKey(to="User", to_field='id', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        db_table = "Article"
        verbose_name_plural = "文章表"


# 赞踩文章关系表
class ThumbUp(models.Model):
    article = models.ForeignKey(to="Article", to_field="id", verbose_name="文章id", on_delete=models.CASCADE)
    user = models.ForeignKey(to="User", to_field='id', verbose_name="用户ID", on_delete=models.CASCADE)
    is_thumb_up = models.BooleanField()

    class Meta:
        db_table = "ThumbUp"
        verbose_name_plural = "赞踩文章关系表"
        unique_together = (("article", "user"), )


# 评论表
class Comment(models.Model):
    content = models.TextField(verbose_name="评论内容")
    ctime = models.DateTimeField(auto_now=True, verbose_name="评论时间")
    user = models.ForeignKey(to="User", to_field='id', on_delete=models.CASCADE, verbose_name="评论人")
    article = models.ForeignKey(to="Article", to_field='id', on_delete=models.CASCADE, verbose_name="评论文章")
    parent_comment = models.ForeignKey(to="Comment", to_field='id', on_delete=models.CASCADE,
                                       verbose_name="父评论", null=True, blank=True)

    def __str__(self):
        return self.user.username + "--->" + self.content

    class Meta:
        db_table = "Comment"
        verbose_name_plural = "评论表"


# 报障表
class Trouble(models.Model):
    title = models.CharField(max_length=64, verbose_name="报障标题")
    detail = models.TextField(verbose_name="故障描述")
    sender = models.ForeignKey(to="User", to_field="id", on_delete=models.CASCADE, related_name="sender", verbose_name="提交者")
    ctime = models.CharField(max_length=32, verbose_name="创建时间")
    status_choices = ((1, "未处理"), (2, "处理中"), (3, "已处理"), )
    status = models.IntegerField(choices=status_choices, verbose_name="障单状态")
    handler = models.ForeignKey(to="User", to_field="id", on_delete=models.CASCADE, null=True, blank=True)
    solve_plan = models.TextField(verbose_name="解决方案", null=True, blank=True)
    stime = models.CharField(max_length=32, verbose_name="解决时间", null=True, blank=True)
    evaluate_choices = ((1, "活儿不行"), (2, "一般"), (3, "活儿很好"), )
    evaluate = models.IntegerField(choices=evaluate_choices, verbose_name="评价", null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = "Trouble"
        verbose_name_plural = "报障表"


# 权限管理相关表


# 角色表
class Role(models.Model):
    caption = models.CharField(max_length=32)

    class Meta:
        db_table = "role"
        verbose_name_plural = '角色表'

    def __str__(self):
        return self.caption


# 用户角色关联表
class User2Role(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)

    class Meta:
        db_table = "user2role"
        verbose_name_plural = '用户分配角色'

    def __str__(self):
        return "%s-%s" % (self.user.username, self.role.caption,)


# 权限表
class Action(models.Model):
    # get  获取用户信息1
    # post  创建用户2
    # delete 删除用户3
    # put  修改用户4
    caption = models.CharField(max_length=32)
    code = models.CharField(max_length=32)

    class Meta:
        db_table = 'action'
        verbose_name_plural = '操作表'

    def __str__(self):
        return self.caption


# 1    菜单1     null
# 2    菜单2     null
# 3    菜单3     null
# 4    菜单1.1    1
# 5    菜单1.2    1
# 6    菜单1.2.1  4
# 无最后一层
class Menu(models.Model):
    caption = models.CharField(max_length=32)
    parent = models.ForeignKey('self', related_name='p', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return "%s" % (self.caption,)


# URL表
class Permission(models.Model):
    # http://127.0.0.1:8001/user.html  用户管理 1
    # http://127.0.0.1:8001/order.html 订单管理 1
    caption = models.CharField(max_length=32)
    url = models.CharField(max_length=64)
    menu = models.ForeignKey(Menu, null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        db_table = 'permission'
        verbose_name_plural = 'URL表'

    def __str__(self):
        return "%s-%s" % (self.caption, self.url,)


# URL跟权限关联表
class Permission2Action(models.Model):
    permission = models.ForeignKey(Permission, on_delete=models.CASCADE)
    action = models.ForeignKey(Action, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '权限表'

    def __str__(self):
        return "%s-%s:-%s?t=%s" % (self.permission.caption, self.action.caption, self.permission.url, self.action.code,)


# 角色跟权限关联表
class Permission2Action2Role(models.Model):
    p2a = models.ForeignKey(Permission2Action, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '角色分配权限'

    def __str__(self):
        return "%s==>%s" % (self.role.caption, self.p2a,)

web/views/my_home.py
from django.shortcuts import render, redirect, HttpResponse
from django.urls import reverse

from repository import models
from utils.pageNation import Pagenation
import json

PER_PAGE = 5


# 将查询全部和查询某个分类的共同部分封装起来
def base(surfix):
    # 选出该后缀对应的博客表以及关联的用户
    blog = models.Blog.objects.filter(surfix=surfix).select_related('user').first()  # 只进行一次查询
    if not blog:
        path = reverse("home", kwargs={"category": 0})
        return redirect(path)
    # 筛选出对应的时间文章
    article_by_time = models.Article.objects.raw("SELECT id, COUNT(id) AS num, DATE_FORMAT(ctime, '%%Y-%%m') "
                                                 "AS create_time, user_id FROM Article WHERE user_id={0} "
                                                 "GROUP BY create_time".format(blog.user_id))

    articles = models.Article.objects.filter(user=blog.user)
    return {
        "blog": blog,
        "article_by_time": article_by_time,
        "articles": articles
    }


# 博客个人主页————显示全部文章
def my_home(request, surfix):
    dic = base(surfix)
    return render(request, "my_home/my_home.html", dic)


# 博客个人主页————筛选文章
def article_filter(request, surfix, category, num):
    dic = base(surfix)
    # 进行分类
    if category == "tag":
        # 查询出该tag下的所有文章
        tag = models.Tag.objects.get(id=num)
        articles = models.Article.objects.filter(tag=tag, user=dic['blog'].user)
    elif category == 'category':
        # 查询出该category下的所有文章
        categorys = models.Category.objects.get(id=num)
        articles = models.Article.objects.filter(category=categorys, user=dic['blog'].user)
    else:
        articles = models.Article.objects.filter(user=dic['blog'].user).extra(
            where=['date_format(ctime, "%%Y-%%m")=%s'], params=[num, ])
    dic["articles"] = articles
    return render(request, "my_home/my_home.html", dic)


# 文章详情
def article_detail(request, surfix, article_id):
    dic = base(surfix)
    # 查询出该篇文章
    article = models.Article.objects.get(id=article_id)
    dic['article'] = article
    # 检查用户是否登录
    dic['is_login'] = True if request.session.get('user', None) else False
    # 获取评论
    comment = article.comment_set.all()
    # 给评论排序（将子评论插到父评论下）
    sorted_comment = sort_comment(comment)
    comments = sorted_comment[:PER_PAGE]
    dic['comments'] = comments
    # 给评论分页
    path = reverse("comment_page_nation")
    page_obj = Pagenation(len(sorted_comment), 1, PER_PAGE, url=path)
    dic['page_obj'] = page_obj
    return render(request, "my_home/article_detail.html", dic)


# 给评论排序
def sort_comment(comment_query):
    """
    [
        {
              id: 1,
              content: "",
              ctime: "",
              user: "",
              article: "",
              child: [
                  {
                      id: 1,
                      content: "",
                      ctime: "",
                      user: "",
                      article: "",
                      child: {...}
                  },
                  {...}
              ]
          },
        {...}
    ]
    :param comment_query:
    :return:
    """
    ret_dic = []   # 最终所有的评论都会放到这个数组里面
    dynamic_dic = {}   # 临时存放所有评论的字典
    for comment in comment_query:
        # 将querySet转成字典
        dynamic_dic[comment.id] = {
            'id': comment.id,
            'content': comment.content,
            'ctime': comment.ctime,
            'user': comment.user,
            'parent_id': comment.parent_comment_id,
            'child': [],
        }

    for comment in dynamic_dic.values():
        # 查看该条评论有没有父id，如果没有就把它放到根目录下
        if not comment['parent_id']:
            ret_dic.append(comment)
        else:
            # 如果有父id，就把该条评论放到父评论的child数组里面
            dynamic_dic[comment['parent_id']]['child'].append(comment)
    return ret_dic     # 返回这个数组


# 保存评论
def save_comment(request):
    message = dict()
    if request.session.get("user", None):
        # 获取评论内容
        comment_content = request.POST.get("comment_content", None)
        # 获取本篇文章的id
        article_id = request.POST.get("article_id", None)
        if comment_content:
            # 将评论存入数据库
            # 获取用户ID
            user_id = request.session['user']['id']
            try:
                models.Comment.objects.create(content=comment_content, user_id=int(user_id), article_id=int(article_id))
                message['status'] = True
                message['info'] = "评论成功"
            except Exception:
                message['status'] = False
                message['info'] = "数据插入失败"
        else:
            message['status'] = False
            message['info'] = '评论内容无效'
    else:
        message['status'] = False
        message['info'] = '未登录'
    return HttpResponse(json.dumps(message))


# 评论分页
def comment_page_nation(request):
    # 获取分页
    page = request.POST.get("page", None)
    if page:
        try:
            page_num = int(page)
        except Exception:
            page_num = 1
    else:
        page_num = 1
    # 查询属于该篇文章的该篇分页的评论数据
    article_id = request.POST.get("article_id")
    comment = models.Comment.objects.filter(article_id=article_id)
    # 给评论排序（将子评论插到父评论下）
    sorted_comment = sort_comment(comment)
    # 准备分页
    path = reverse("comment_page_nation")
    page_obj = Pagenation(len(sorted_comment), page_num, PER_PAGE, url=path)

    comments = sorted_comment[page_obj.start_index:page_obj.end_index]
    # 检查登录情况
    is_login = True if request.session.get('user', None) else False
    return render(request, "my_home/comment.html", {
        "comments": comments,
        "page_obj": page_obj,
        'is_login': is_login,
        'article_id': article_id,
    })


# 赞踩关系处理
def thumb(request):
    # 获取文章id
    article_id = request.POST.get('article_id', None)
    # 获取用户
    user = request.session['user']
    # 是否点赞
    is_thumb_up = bool(int(request.POST.get('is_thumb_up')))
    # 将点赞信息储存
    try:
        models.ThumbUp.objects.create(article_id=article_id, user_id=user['id'], is_thumb_up=is_thumb_up)
    except:
        return HttpResponse(0)
    return HttpResponse(1)


# 回复评论
def re_comment(request):
    # 获取评论信息
    parent_id = request.POST.get("parent_id", None)
    comment_content = request.POST.get("comment_content", None)
    article_id = request.POST.get("article_id", None)
    # 获取用户
    user = request.session['user']
    # 将评论存到数据库
    try:
        models.Comment.objects.create(
            content=comment_content,
            user_id=user['id'],
            article_id=article_id,
            parent_comment_id=parent_id,
        )
    except:
        return HttpResponse("0")
    return HttpResponse("1")

templates/my_home/article_detail.html
{% extends "my_home/base.html" %}
{% load staticfiles %}
{% load count_article %}
{% load load_comment %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block change_area %}
    <div class="article_detail">
        <div class="a-title">
            {{ article.title }}
        </div>
        <div class="a-content">
            {{ article.detail|safe }}
        </div>
        <div class="a-footer">
            <div class="thumb-up clearfloat">
                <div id="thumb-up" class="up con" data-article-id="{{ article.id }}">
                    <i class="glyphicon glyphicon-thumbs-up"></i>
                    <span>{{ article.id|get_thumb }}</span>
                </div>
                <div id="thumb-down" class="down con" data-article-id="{{ article.id }}">
                    <i class="glyphicon glyphicon-thumbs-down"></i>
                    <span>{{ article.id|get_thumb_down }}</span>
                </div>
            </div>
            <div class="author-info">
                {{ article.ctime }} <a href="javascript:void(0);">{{ blog.title }}</a> 评论({{ article.comment_set.count }}) 阅读(14)
            </div>
            <div class="warning clearfloat">
                <div class="img">
                    <img src="{% static 'images/my_home/warning.png' %}" alt="IMG">
                </div>
                <div class="word">
                    <span>作者：<a href="#">{{ blog.title }}</a></span><br>
                    <span>出处：<a href="#">http://www.cnblogs.com/articles</a></span><br>
                    <span>本文版权归作者所有，欢迎转载，但未经作者同意必须保留此段声明，且在文章明显位置给出原文链接</span>
                </div>
            </div>
            <div class="comment">
                <div class="c-title">评论列表</div>
                {% for comment in comments %}
                <div class="c-content">
                  <div class="c-comment">
                       <div class="c-person"><a href="javascript:void(0);">
                           {{ comment.user.username }}</a>
                           <span>{{ comment.ctime|date:'Y-m-d' }} {{ comment.ctime|time:'h:i' }}</span>
                       </div>
                       <div class="content">{{ comment.content|safe }}</div>
                       <!-- 在这里加载子评论 -->
                       {% load_comment comment.child %}
                  </div>
                   <div class="return re-comment" data-nid="{{ comment.id }}" data-user="{{ comment.user.username }}">
                        <a href="javascript:void(0);">回复</a>
                   </div>
                </div>
                {% endfor %}
                <div class="page-nation">
                    <!-- 分页 -->
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                        {% if page_obj.current_page == 1 %}
                            <li class="disabled">
                                <a href="javascript:void(0);" aria-label="Previous">
                                    <span aria-hidden="true">上一页</span>
                                </a>
                            </li>
                        {% else %}
                            <li>
                                <a href="javascript:void(0);" aria-label="Previous"
                                   onclick="page_click(this, '{{ page_obj.url }}', {{ page_obj.previous_page }}, {{ article.id }});">
                                    <span aria-hidden="true">上一页</span>
                                </a>
                            </li>
                        {% endif %}


                            {% for page in page_obj.page_nation %}
                                {% if page_obj.current_page == page %}
                                    <li class="active"><a href="javascript:void(0);">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="javascript:void(0);"
                                    onclick="page_click(this, '{{ page_obj.url }}', {{ page }}, {{ article.id }});">{{ page }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.current_page == page_obj.max_page %}
                                <li class="disabled">
                                    <a href="javascript:void(0);" aria-label="Next">
                                        <span aria-hidden="true">下一页</span>
                                    </a>
                                </li>
                            {% else %}
                                <li>
                                    <a href="javascript:void(0);" aria-label="Next"
                                    onclick="page_click(this, '{{ page_obj.url }}', {{ page_obj.next_page }}, {{ article.id }});">
                                        <span aria-hidden="true">下一页</span>
                                    </a>
                                </li>
                            {% endif %}

                        </ul>
                    </nav>
                </div>
                <div class="write-comment">
                    {% if is_login %}
                        <textarea name="comment" id="comment"></textarea>
                    {% else %}
                        <div class="cover">
                            需要<a href="{% url 'show_login_page' %}">登录</a>才能发表评论哦~~
                        </div>
                        <textarea name="comment" id="comment"></textarea>
                    {% endif %}
                    <div id="commit">
                        <button type="button" class="btn btn-info comment-commit" onclick="comment_click();">提交评论</button>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- 模态对话框 -->
    <div class="modal fade" id="comment_Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel">回复评论</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="message-text" class="control-label">回复</label>
                        <input id="re-comment" type="text" name="comment" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button id="submit_comment" type="button" class="btn btn-primary">提交</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script>
        // 获取评论内容
        function comment_click(){
            var comment_content = editor.html();
            if(comment_content !== ""){
                $.ajax({
                    url: "{% url 'save_comment' %}",
                    type: "post",
                    dataType: 'JSON',
                    data: {"comment_content": comment_content, "article_id": {{ article.id }}},
                    success: function(arg){
                        if(arg.status){
                            window.location.reload();
                        }
                        alert(arg.info);
                    }
                });
            }
        }

        // 分页
        function page_click(othis, url, page, article_id){
            $.ajax({
                url: url,
                type: 'post',
                data: {'page': page, "article_id": article_id},
                success: function(arg){
                    $(".comment").html(arg);
                    // 加载富文本
                    var sc = document.createElement("script");
                    sc.src = "{% static 'js/my_home.js' %}";
                    $("body").append(sc);
                    $(sc).remove();
                }
            });
        }

        // 赞踩关系
        $("#thumb-up").click(function(){
            // 发送点赞信息
            // 获取文章id
            let othis = $(this);
            let article_id = $(this).data("article-id");
            $.ajax({
                url: '{% url "thumb" %}',
                type: 'post',
                data: {'article_id': article_id, 'is_thumb_up': 1},
                success: function(args){
                    if(args === '0'){
                        alert('您已为该文章点过赞了');
                    }else{
                        alert('点赞成功');
                    }
                    // 刷新点赞数
                    othis.children('span').html({{ article.id|get_thumb }} + 1);
                }
            });
        });
        $('#thumb-down').click(function () {
            // 踩本篇文章
            // 获取文章id
            let article_id = $(this).data("article-id");
            let othis = $(this);
            $.ajax({
                url: '{% url "thumb" %}',
                type: 'post',
                data: {'article_id': article_id, 'is_thumb_up': 0},
                success: function(args){
                    if(args === '0'){
                        alert('您已为该文章点过赞了');
                    }else{
                        alert('已踩');
                    }
                    // 刷新踩文章数
                    othis.children('span').html({{ article.id|get_thumb_down }} + 1);
                }
            });
        });

        // 回复评论
        $(".comment").on('click', ".re-comment", function(){
            // 获取评论的id
            let nid = $(this).data("nid");
            // 获取评论人的名字
            let username = $(this).data("user");
            // 激活模态对话框
            $("#re-comment").attr('placeholder', '回复' + username + ":");
            $("#comment_Modal").modal("show");

            // 激活click点击事件
            $('#submit_comment').click(function(){
                // 获取评论
                let re_comment = $("#re-comment").val().trim();
                if(re_comment !== ""){
                    // 将父评论的id、回复评论内容、文章id发送
                    $.ajax({
                        url: '{% url "re_comment" %}',
                        type: "post",
                        data: {'parent_id': nid, 'comment_content': re_comment, 'article_id': {{ article.id }}},
                        success (args){
                            if(args === "0"){
                                alert('服务器开小差啦，稍后再试吧~~~');
                            }else{
                                alert('提交成功');
                                window.location.reload();    // 刷新页面
                            }
                        }
                    });
                }
            });
        });
    </script>
{% endblock %}

templates/my_home/base.html
{% load staticfiles %}
{% load count_article %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/my_home.css' %}">
    <link rel="stylesheet" href="{% static "plugins/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/bootstrap/css/bootstrap.min.css" %}">
</head>
<body>
    <div id="wrapping">
        <div class="header">
            <div class="personnal-title">
                <a href="#">{{ blog.title }}</a>
            </div>
        </div>
        <div class="friendly-links">
            <ul class="nav-list click-list">
                <li class="active"><a href="{% url "home" 0 %}" style="display: block;">首页</a></li>
                <li><a href="{% url "my_home" blog.surfix %}" style="display: block;">个人首页</a></li>
                <li><a href="{% url 'add_article' %}" style="display: block;">新文章</a></li>
                <li><a href="{% url 'index' %}" style="display: block;">管理</a></li>
            </ul>
        </div>
        <div class="body clearfloat">
            <div class="menu">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">公告</h3>
                    </div>
                    <div class="panel-body">
                        <ul class="inform-list">
                            <li>昵称：{{ blog.user.username }}</li>
                            <li>粉丝：{{ blog.user.fans.all.count }}</li>
                            <li>关注：{{ blog.user.refans.all.count }}</li>
                            <li>邮箱：{{ blog.user.email }}</li>
                        </ul>
                    </div>
                </div>
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title">标签</h3>
                    </div>
                    <div class="panel-body">
                        <ul class="tag-list">
                            {% for tag in blog.tag_set.all %}
                            <li><a href="{% url 'article_filter' blog.surfix 'tag' tag.id %}">{{ tag.caption }}({{ tag|count_tag:blog.user }})</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <h3 class="panel-title">分类</h3>
                    </div>
                    <div class="panel-body">
                        <ul class="category-list">
                            {% for category in blog.category_set.all %}
                            <li>
                                <a href="{% url 'article_filter' blog.surfix 'category' category.id %}">
                                    {{ category.caption }}({{ category|count_category:blog.user }})
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">时间</h3>
                    </div>
                    <div class="panel-body">
                        <ul class="time-list">
                            {% for date_list in article_by_time %}
                                <li>
                                    <a href="{% url 'article_filter' blog.surfix 'time' date_list.create_time %}">
                                        {{ date_list.create_time }}({{ date_list.num }})
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            {% block change_area %}{% endblock %}
        </div>
        <div class="footer">
            Design By ©
            <span>Jin同学</span>
        </div>
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static "plugins/kindeditor/kindeditor-all-min.js" %}"></script>
    <script src="{% static 'js/my_home.js' %}"></script>
    {% block js %}
    {% endblock %}
</body>
</html>